default = [
    {
        "group": "Action movie",
        'title': 'Đế chế Ultron',
        'description': 'Ultron was created by Iron Man to protect the world on his behalf. But the idea That failed when Ultron became out of control and turned into a cold-blooded killing machine.',
        "year": 2021,
        "rating": "R",
        "runtime": "2h 12m",
        "price": 150,
        "director": "James Gunn",
        "cast": "Margot Robbie, Idris Elba, John Cena, Daniela Melchior",
        "category": "Action, Adventure, Comedy, Sci-Fi",
        "poster_url": "marvels-avengers-age-of-ultron.jpeg",
        "video_url": "Avengers_ Age of Ultron.mp4",
        "trailer": "Avengers_ Age of Ultron.mp4"
    }
] 

new_arrival = [
    {
        "group": "New arrival",
        "title": "Shang-Chi and the Legend of the Ten Rings",
        "description": "Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.",
        "year": 2021,
        "rating": "PG-13",
        "runtime": "2h 12m",
        "price": 115,
        "director": "Destin Daniel Cretton",
        "cast": "Simu Liu, Awkwafina, Tony Chiu-Wai Leung",
        "category": "Action, Adventure, Fantasy, Sci-Fi",
        "poster_url": "1. Shang Chi.png",
        "video_url": "1. Film_ShangChi.mp4",
        "trailer": "1. Trailer_ShangChi.mp4"
    },
    {
        "group": "New arrival",
        "title": "The Medium",
        "description": "A horrifying story of a shaman's inheritance in the Isan region of Thailand. What could be possessing a family member might not be the Goddess they make it out to be.",
        "year": 2021,
        "rating": "R",
        "runtime": "2h 10m",
        "price": 250,
        "director": "Chantavit Dhanasevi",
        "cast": "Narilya Gulmongkolpech, Sawanee Utoomma, Sirani Yankittikan",
        "category": "\nHorror",
        "poster_url": "2. The Medium.png",
        "video_url": "2. Trailer + Film_ The medium.mp4",
        "trailer": "2. Trailer + Film_ The medium.mp4"
    },
    {
        "group": "New arrival",
        "title": "Black Widow",
        "description": "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises.",
        "year": 2021,
        "rating": "PG-13",
        "runtime": "2h 14m",
        "price": 150,
        "director": "\nCate Shortland",
        "cast": "Scarlett Johansson, Florence Pugh, David Harbour",
        "category": "Action, Adventure, Sci-Fi",
        "poster_url": "3. Black Widow.png",
        "video_url": "1. Film_ShangChi.mp4",
        "trailer": "1. Trailer_ShangChi.mp4"
    },
    {
        "group": "New arrival",
        "title": "Hitman's Wife's Bodyguard",
        "description": "The bodyguard Michael Bryce continues his friendship with assassin Darius Kincaid as they try to save Darius' wife Sonia.",
        "year": 2021,
        "rating": "R",
        "runtime": "1h 40m",
        "price": 150,
        "director": "Tom O'Connor",
        "cast": "Ryan Reynolds, Samuel L. Jackson, Salma Hayek",
        "category": "Action, Comedy, Crime, Thriller",
        "poster_url": "5. Hitman_s Wife_s Bodyguard.png",
        "video_url": "1. Film_ShangChi.mp4",
        "trailer": "1. Trailer_ShangChi.mp4"
    },
    {
        "group": "New arrival",
        "title": "Seance",
        "description": "Camille, a young woman who arrives at the Fairfield Academy following one of the student's untimely and violent death.",
        "year": 2021,
        "rating": "R",
        "runtime": "1h 32m",
        "price": 160,
        "director": "Simon Barrett",
        "cast": "Suki Waterhouse, Madisen Beaty, Inanna Sarkis",
        "category": "Horror, Mystery",
        "poster_url": "6. Seance.png",
        "video_url": "1. Film_ShangChi.mp4",
        "trailer": "1. Trailer_ShangChi.mp4"
    },
]

action = [
    {

        "group": "Action movie",
        "title": "The Suicide Squad",
        "description": "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
        "year": 2021,
        "rating": "R",
        "runtime": "2h 12m",
        "price": 200,
        "director": "James Gunn",
        "cast": "Margot Robbie, Idris Elba, John Cena, Daniela Melchior",
        "category": "Action, Adventure, Comedy, Sci-Fi",
        "poster_url": "4. The Suicide Squad.png",
        "video_url": "4. Film_The Suicide Squad.mp4",
        "trailer": "4. Trailer_The Suicide Squad.mp4"
    },
    {
        "group": "Action movie",
        "title": "Those Who Wish Me Dead",
        "description": "A teenage murder witness finds himself pursued by twin assassins in the Montana wilderness with a survival expert tasked with protecting him -- and a forest fire threatening to consume them all.",
        "year": 2021,
        "rating": "R",
        "runtime": "1h 40m",
        "price": 150,
        "director": "Taylor Sheridan",
        "cast": "Angelina Jolie, Nicholas Hoult, Finn Little",
        "category": "Action, Crime, Drama, Thriller",
        "poster_url": "8. Those who wish me dead.png",
        "video_url": "8_Film_Those who wish me dead.mp4",
        "trailer": "8_Trailer_Those who wish me dead.mp4"
    },
    {
        "group": "Action movie",
        "title": "Hard Hit",
        "description": "Sung-Kyu (Jo Woo-Jin) works as a manager at a bank branch. he sets off to drive his kids to school and then go to work, but he receives a phone call without a caller ID. The caller tells him \"when you get out the car, a bomb will explode.\"",
        "year": 2021,
        "rating": "PG-13",
        "runtime": "1h 34m",
        "price": 100,
        "director": "Changju Kim",
        "cast": "Ji Chang-Wook, Woo-jin Jo, Ji-ho Kim",
        "category": "Drama, Thriller",
        "poster_url": "10. Hard hit.png",
        "video_url": "10_Film_Hard Hit.mp4",
        "trailer": "10_Trailer_Hard hit.mp4"
    },
    {
        "group": "Action movie",
        "title": "Face Off: 48H",
        "description": "Ly Hai returns to his action movies. Magnificent context with serious investment, the action masterpiece Vietnamese Flip Face 48h will tell a dramatic journey to escape, choking to the last minute.",
        "year": 2021,
        "rating": "PG-13",
        "runtime": "1h 50m",
        "price": 250,
        "director": "Ly Hai",
        "cast": "Le Ha Anh, Tiet Cuong, Huynh Dong",
        "category": "Action, Comedy",
        "poster_url": "14. Face off.png",
        "video_url": "14. Film_Face off.mp4",
        "trailer": "14. Trailer_Face off.mp4"
    },
]

hot = [
    {
        "group": "Hot movie",
        "title": "The Conjuring: The Devil Made Me Do It",
        "description": "The Warrens investigate a murder that may be linked to a demonic possession.",
        "year": 2021,
        "rating": "R",
        "runtime": "1h 52m",
        "price": 300,
        "director": "Michael Chaves",
        "cast": "Vera Farmiga, Patrick Wilson, Sterling Jerins, Julian Hilliard",
        "category": "Horror, Mystery, Thriller",
        "poster_url": "7. The Conjuring.png",
        "video_url": "7_Film_The Conjuring.mp4",
        "trailer": "7_Trailer_The Conjuring.mp4"
    },
    {
        "group": "Hot movie",
        "title": "Dark Spell",
        "description": "Dark Spell is a story about the girl named Zhenya who suffers from being in love with her husband that has left her, so she decides to bring him back. Desperate heroine casts a spell called \"Black Wedding\", which is a magical ritual known for its great power and irreversibility. After the ritual, her beloved husband comes back, although his love becomes more like an obsession: he is even ready to kill Zhenya, so as not to give her to anyone. When the maddened husband dies, the spell does not stop: because even death will not part those who were betrothed by the demon of black wedding.",
        "year": 2021,
        "rating": "R",
        "runtime": "1h 32m",
        "price": 150,
        "director": "Svyatoslav Podgaevskiy",
        "cast": "Yana Yenzhayeva, Konstantin Beloshapka, Ilya Yermolov",
        "category": "Drama, Fantasy, Horror, Romance, Thriller",
        "poster_url": "9_Dark Spell.png",
        "video_url": "9_Film + Trailer_Dark Spell.mp4",
        "trailer": "9_Film + Trailer_Dark Spell.mp4"
    },
    {
        "group": "Hot movie",
        "title": "Thien Than Ho Menh",
        "description": "After the shocking suicide of a young pop star, her backup singer finds herself living a parallel life. But is her success earned, or is it being aided by occult forces?",
        "year": 2021,
        "rating": "R",
        "runtime": "2h 4m",
        "price": 175,
        "director": "\nVictor Vu",
        "cast": "\nAmee, Truc Anh",
        "category": "\nHorror, Thriller",
        "poster_url": "11. Thien than ho menh.png",
        "video_url": "7_Film_The Conjuring.mp4",
        "trailer": "7_Trailer_The Conjuring.mp4"
    },
]

horror = [
    {
        "group": "Horror movie",
        "title": "Wrong Turn",
        "description": "Friends hiking the Appalachian Trail are confronted by 'The Foundation', a community of people who have lived in the mountains for hundreds of years.",
        "year": 2021,
        "rating": "R",
        "runtime": "1h 49m",
        "price": 1.5,
        "director": "Mike P. Nelson",
        "cast": "Charlotte Vega, Adain Bradley, Bill Sage",
        "category": "\nHorror, Thriller",
        "poster_url": "12. Wrong turn.png",
        "video_url": "15. Film_Malignant.mp4",
        "trailer": "15. Trailer_Malignant.mp4"
    },
    {
        "group": "Horror movie",
        "title": "Great White",
        "description": "A fun filled flight to a remote atoll turns into a nightmare for five passengers when their seaplane is destroyed in a freak accident and they are trapped on a raft, 100 miles from shore with man-eating sharks lurking beneath the surface.",
        "year": 2021,
        "rating": "R",
        "runtime": "1h 31m",
        "price": 160,
        "director": "Martin Wilson",
        "cast": "Katrina Bowden, Aaron Jakubenko, Kimie Tsukakoshi",
        "category": "Horror, Thriller",
        "poster_url": "13. Great White.png",
        "video_url": "15. Film_Malignant.mp4",
        "trailer": "15. Trailer_Malignant.mp4"
    },
    {
        "group": "Horror movie",
        "title": "Malignant",
        "description": "Madison is paralyzed by shocking visions of grisly murders, and her torment worsens as she discovers that these waking dreams are in fact terrifying realities.",
        "year": 2021,
        "rating": "R",
        "runtime": "1h 51m",
        "price": 170,
        "director": "James Wan",
        "cast": "Annabelle Wallis, Maddie Hasson, George Young",
        "category": "Crime, Horror, Mystery, Thriller",
        "poster_url": "15. Malignant.png",
        "video_url": "15. Film_Malignant.mp4",
        "trailer": "15. Trailer_Malignant.mp4"
    }
]
